services:
  - type: web
    name: todo-app
    env: ruby
    plan: starter           # or whatever plan you’re on
    buildCommand: bundle install && bundle exec rails assets:precompile
    releaseCommand: bundle exec rails db:migrate
    startCommand: bundle exec rails server -p $PORT
